### ISSUE TITLE
What is secret.json?

### ISSUE THREAD

**Issue by albertyw** [Naramsim/GithubOriginalStreak#34]
And why isn't it checked into the repository?  It's pretty easy to find the token.  It seems to point to https://api.github.com/gists/5d89d59e4e9355ff5e8316b40dcebf09

**Comment by Naramsim** [comment]
In secret.json there a Gist only token. I need it to update a gist.
I know that someone could use it in evil ways(delete the gist).
But I'm pretty sure that since this is an open source free project no one will be evil

It is not checked in the repo because Github automatically disables valid token if pushed to a repository

**Comment by wbraswell** [comment]
@Naramsim 
Do you have a local or online backup of the gist, in case of some "evil" person?

**Comment by Naramsim** [comment]
Yes, of course

**Comment by wbraswell** [comment]
Okay great!  :+1:
