### ISSUE TITLE
Enhancement / Set Urls

### ISSUE THREAD

**Issue by daberkow** [Naramsim/GithubOriginalStreak#60]
I work somewhere were we run github enterprise, it would be cool to let us enter custom URLs. Secondarily, if somehow we could ignore the weekends. :D

**Comment by Naramsim** [comment]
It is hard to allow custom URLs since we have to allow every URL and check if the calendar is present.
Right now we allow only [\*.github.com\*](https://github.com/Naramsim/GithubOriginalStreak/blob/master/chrome/manifest.json#L25)

If I understand one can run Github enterprise on his own servers, right? Having a custom domain?

**Comment by daberkow** [comment]
Yeah it can be any domain at your company or school, if there was an easy way to allow us to edit the regex that would be awesome!

**Comment by Naramsim** [comment]
Hi, there is no way to let users alter the manifest of an extension. And I don´t want to run the script on all web pages (match them all) since it will produce unnecessary work and scare users. Also, Firefox does not support dynamic permissions ([Chrome yes](https://developer.chrome.com/extensions/permissions))

So one thing you can do is modify by yourself this extension and allow your custom domain, then load it from your fs. Just edit [this file](https://github.com/Naramsim/GithubOriginalStreak/blob/master/chrome/manifest.json#L18-L25)

One thing you should know is that every time you load an untrusted extension in Chrome, it will notify you about it.

If more people would like to add this functionality to the extension, I will re-open this issue

**Comment by Naramsim** [comment]
https://github.com/bfred-it/webext-domain-permission-toggle
